name: Publish Article
on:
  push:
    paths:
      - 'articles/*.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'Lifeni-Space/Blog'
          submodules: 'true'

      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: git submodule update --remote
      - run: yarn
      - run: yarn clean
      - run: yarn build

      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: 'public/*'
          target: '/home/github/blog'
          overwrite: true
